---
- name: Update packages
  hosts: all
  connection: ssh
  become: true
  tasks:
    - name: Apt dist upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
    - name: Update Tailscale
      apt:
        name: tailscale
        state: latest
        update_cache: yes
