name: ansible


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'foo'
        required: true
        type: string

# assumes that the ssh key used here already has its pub key added to the server we are running against
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job
  run_ansible_over_tailscale:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Initialise Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./
          playbook: update.yml
          key: ${{secrets.SSH_KEY}}
          options: |
            --user ${{ inputs.username }}
