---
name: run_playbook

on:
  workflow_call:
      inputs:
        user:
          required: true
          type: string
        host:
          required: true
          type: string
        playbook:
          required: true
          type: string
  workflow_dispatch:
    inputs:
      user:
        description: 'Run ansible as this user'
        default: 'USER'
        required: true
        type: string
      host:
        description: 'Host to run ansible against'
        default: 'HOST'
        required: true
        type: string
      playbook:
        description: 'Ansible playbook to run'
        default: 'PLAYBOOK'
        required: true
        type: string

jobs:
  run_ansible_over_tailscale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Connect to Tailnet
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run ${{ inputs.playbook }} Playbook against ${{ inputs.host }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./
          playbook: ${{ inputs.playbook }}.yml
          key: ${{ secrets.SSH_KEY }} # assumes that the corresponding pub key was added to the host we are running against
          inventory: |
            [all]
            ${{ inputs.host }}
          options: |
            --user ${{ inputs.user }}
