---
name: run_playbook

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Username'
        default: 'USERNAME'
        required: true
        type: string
      host:
        description: 'Host'
        default: 'HOST'
        required: true
        type: string
      playbook:
        description: 'Playbook'
        default: 'PLAYBOOK'
        required: true
        type: string

# assumes that the ssh key used here already has its pub key added to the server we are running against
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_ansible_over_tailscale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Connect to Tailnet
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Run ${{ inputs.playbook }} Playbook against ${{ inputs.host }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./
          playbook: ${{ inputs.playbook }}.yml
          key: ${{ secrets.SSH_KEY }}
          inventory: |
            [all]
            ${{ inputs.host }}
          options: |
            --user ${{ inputs.user }}
