---
name: scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: '11 4 * * *'
jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        host: [raspberrypi, test-vm, vpn-1, aws-instance, aws-instance-2, ubuntupi4, ubuntu-pizero2w, ubuntu-server, tailscale-test, pizero2w-1, pizero2w-2]
    uses: ./.github/workflows/main.yml
    with:
      user: "pi"
      host: ${{ matrix.host }}
      playbook: "update"
    secrets: inherit
