---
name: schedule_playbook_run

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Run ansible as this user'
        default: 'USER'
        required: true
        type: string
      host:
        description: 'Host to run ansible against'
        default: 'HOST'
        required: true
        type: string
      playbook:
        description: 'Ansible playbook to run'
        default: 'PLAYBOOK'
        required: true
        type: string
jobs:
  run_ansible_over_tailscale:
      uses: ./.github/workflows/run_playbook.yml
      with:
        user: ${{ inputs.user }}
        host: ${{ inputs.host }}
        playbook: ${{ inputs.playbook }}
      secrets:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        key: ${{ secrets.SSH_KEY }}
      
