---
name: scheduled

on:
  schedule:
    - cron: '11 4 * * *'
jobs:
  update:
      uses: ./.github/workflows/ansible.yml
      with:
        user: "pi"
        host: "raspberrypi"
        playbook: "update"
      secrets: inherit
      
