---
name: scheduled

on:
  schedule:
    - cron: '11 4 * * *'
jobs:
  update:
      uses: ./.github/workflows/run_playbook.yml
      with:
        user: ${{ inputs.user }}
        host: ${{ inputs.host }}
        playbook: ${{ inputs.playbook }}
      secrets: inherit
      
