---
name: scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: '11 4 * * *'
jobs:
  update_raspberrypi:
    strategy:
      matrix:
        host: [raspberrypi, pizero2w]
    uses: ./.github/workflows/main.yml
    with:
      user: "pi"
      host: ${{ matrix.host }}
      playbook: "update"
    secrets: inherit
